---
title: 'Problem Set: Explore Many Variables'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Price Histograms with Facet and Color
Note:

```{r Price Histograms with Facet and Color}
library(ggplot2)
data("diamonds")

ggplot(aes(x = price, fill = factor(cut)), data = diamonds) + 
        geom_histogram(binwidth = 200) +
        facet_wrap(~color) +
        scale_color_brewer(type = 'qual') 
 
```

***

## Price vs. Table Colored by Cut
Note:

```{r Price vs. Table Colored by Cut}
ggplot(aes(x = table, y = price, color = cut), data = diamonds) + 
        geom_point() +
        facet_wrap(~color) +
        scale_color_brewer(type = 'qual') +
        scale_x_continuous(breaks = seq(50,80,2), lim = c(50,80)) 

```

***

## Typical Table Value
```{r}
library(reshape2)
d <-dcast(diamonds,table~cut,value.var = 'price')

with(subset(d,!is.na(Ideal) & d$Ideal > 0),summary(Ideal))

with(subset(d,!is.na(Premium) & d$Premium > 0),summary(Premium))

```

***

## Price vs. Volume and Diamond Clarity
```{r}
diamonds$volume = diamonds$x * diamonds$y * diamonds$z
ggplot(aes(x = volume, y = price, color = clarity), data = diamonds) +
        geom_point() + 
        scale_y_log10() + 
        scale_color_brewer(type = 'div') +
        xlim(0, quantile(diamonds$volume, 0.99))


```

*** 

## Proportion of Friendships Initiated
```{r}
pf <- read.delim('pseudo_facebook.tsv')
pf$prop_initiated = pf$friendships_initiated / pf$friend_count

```

***

## prop_initiated vs. tenure
```{r}
pf$year_joined <- floor(2014 - pf$tenure/365)
pf$year_joined.bucket <- cut(pf$year_joined, c(2004, 2009, 2011, 2012, 2014))

ggplot(data = subset(pf, !is.na(year_joined.bucket)), aes(x = tenure, y = prop_initiated, color = year_joined.bucket)) +
    geom_line(stat = 'summary', fun.y = mean)

```

***

## Smoothing prop_initiated vs. tenure
```{r}
ggplot(data = subset(pf, !is.na(year_joined.bucket)), aes(x = tenure, y = prop_initiated, color = year_joined.bucket)) +
    geom_line(stat = 'summary', fun.y = mean) +
    geom_smooth()

```

***

## Largest Group Mean prop_initiated
```{r}
subs<-subset(pf, year_joined > 2012)
mean(subs$prop_initiated, na.rm = T)

```

***

## Price/Carat Binned, Faceted, & Colored
```{r}
ggplot(diamonds, aes(x = cut, y = price/carat)) +
    geom_point(aes(color = diamonds$color), alpha = (1/2), position = position_jitter(width = 0.3)) +
    facet_wrap( ~ clarity) +
    scale_color_brewer(type = 'div')

```

